const systems={
  Dataverse:'Relational data models, security, business logic and governed application foundations.',
  'C# Plugins':'Transactional server-side automation for rules that must execute consistently.',
  'Power Automate':'Human workflows, notifications and service orchestration across Microsoft 365.',
  Azure:'Scalable APIs, asynchronous messaging and integration services beyond the platform boundary.'
};
document.querySelectorAll('.satellite').forEach(button=>button.addEventListener('click',()=>{
  const name=button.dataset.system;document.querySelector('#systemName').textContent=name.toUpperCase();document.querySelector('#systemText').textContent=systems[name];
}));

const tabs={
  experience:{title:'Experience layer',text:'Interfaces that make complex work feel clear, fast and intentional.',skills:['Canvas Apps','Model-driven apps','PCF controls','JavaScript / TypeScript','HTML / CSS','Power Pages'],terminal:['✓ Responsive workspace loaded','✓ Accessible interactions verified','✓ Client API context secured']},
  logic:{title:'Logic layer',text:'Rules placed at the right execution point—from instant UI feedback to transactional enforcement.',skills:['C# plugins','Custom APIs','Power Fx','Business rules','Dataverse events'],terminal:['✓ Pre-validation registered','✓ Idempotency guard active','✓ Trace telemetry enabled']},
  integration:{title:'Integration layer',text:'Resilient connections between Dynamics, Microsoft 365 and external services.',skills:['REST / OData','Microsoft Graph','Azure Functions','Service Bus','Logic Apps'],terminal:['✓ Identity token acquired','✓ Retry policy configured','✓ Dead-letter path monitored']},
  delivery:{title:'Delivery layer',text:'Controlled releases with environment-aware configuration and repeatable quality gates.',skills:['Solutions & ALM','Azure DevOps','Security roles','Environment variables','Power BI'],terminal:['✓ Managed solution validated','✓ Deployment checks passed','✓ Production release ready']}
};

const crmModules={
  sales:{kicker:'DYNAMICS 365 SALES',metric:'REVENUE CLARITY',input:'Leads, accounts, activities and opportunities',build:'Guided selling, scoring, automation and connected data',output:'Cleaner pipeline, faster follow-up and better forecasting'},
  service:{kicker:'DYNAMICS 365 CUSTOMER SERVICE',metric:'CUSTOMER LOYALTY',input:'Cases, conversations, knowledge and service history',build:'Omnichannel routing, agent workspace, SLAs and self-service',output:'Faster resolution, consistent service and stronger retention'},
  field:{kicker:'DYNAMICS 365 FIELD SERVICE',metric:'FIRST-TIME FIX',input:'Work orders, assets, locations and technician capacity',build:'Intelligent scheduling, mobile workflows and asset history',output:'Less travel, higher utilization and reliable on-site service'},
  journeys:{kicker:'DYNAMICS 365 CUSTOMER INSIGHTS',metric:'RELEVANT ENGAGEMENT',input:'Customer profiles, consent, behaviors and interaction signals',build:'Unified segments, real-time journeys and personalized triggers',output:'Timely engagement, consistent journeys and clearer attribution'},
  project:{kicker:'DYNAMICS 365 PROJECT OPERATIONS',metric:'PROFITABLE DELIVERY',input:'Demand, skills, schedules, time, costs and billing',build:'Resource planning, delivery workflows and financial controls',output:'Better utilization, predictable delivery and protected margin'}
};
document.querySelectorAll('[data-crm]').forEach(button=>button.addEventListener('click',()=>{
  document.querySelectorAll('[data-crm]').forEach(item=>item.classList.remove('active'));button.classList.add('active');
  const module=crmModules[button.dataset.crm];
  ['Kicker','Metric','Input','Build','Output'].forEach(key=>document.querySelector(`#crm${key}`).textContent=module[key.toLowerCase()]);
}));
const board=document.querySelector('#boardContent'),terminal=document.querySelector('#terminalCode');
function showTab(key){const t=tabs[key];board.innerHTML=`<p class="tag">CAPABILITY PROFILE</p><h3>${t.title}</h3><p>${t.text}</p><div class="skill-cloud">${t.skills.map(s=>`<span>${s}</span>`).join('')}</div>`;terminal.textContent='';let full=`> inspect ${key}-layer\n\n${t.terminal.join('\n')}\n\nSTATUS: HEALTHY`;let i=0;const timer=setInterval(()=>{terminal.textContent=full.slice(0,++i);if(i>=full.length)clearInterval(timer)},14)}
document.querySelectorAll('.board-nav button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.board-nav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');showTab(btn.dataset.tab)}));showTab('experience');

const missions={growth:{eyebrow:'MISSION 001 / ANONYMIZED CASE STUDY',title:'One workspace. Connected decisions. Clear execution.',summary:'The challenge was coordinating owners, deadlines, external relationships, documents and operational risk across a changing business lifecycle. Identifying client and product details have been intentionally omitted.',details:[['Architecture','Secure relational domain model'],['Automation','Transactional event pipeline'],['Experience','Role-focused workspaces'],['Integration','Documents, calendar and analytics']]},ai:{eyebrow:'MISSION 002 / ANONYMIZED CASE STUDY',title:'AI that belongs inside the workflow.',summary:'The experience combines governed business data, purpose-built interaction and generative assistance directly inside the user workflow. Identifying client and product details have been intentionally omitted.',details:[['Principle','Human review stays visible'],['Interface','Custom interactive controls'],['Context','Grounded enterprise data'],['Result','Less navigation and rework']]},integration:{eyebrow:'MISSION 003 / ANONYMIZED CASE STUDY',title:'Integration is a product, not a pipe.',summary:'External systems fail. Good integration architecture expects it—using asynchronous boundaries, idempotent processing, traceable errors and secure service identities. Identifying client and product details have been intentionally omitted.',details:[['Edge','Secured REST interface'],['Async','Message-based processing'],['Compute','Serverless orchestration'],['Operations','Retry + failure visibility']]}};
const dialog=document.querySelector('#missionDialog');document.querySelectorAll('.mission-open').forEach(btn=>btn.addEventListener('click',()=>{const m=missions[btn.dataset.mission];document.querySelector('#dialogEyebrow').textContent=m.eyebrow;document.querySelector('#dialogTitle').textContent=m.title;document.querySelector('#dialogSummary').textContent=m.summary;document.querySelector('#dialogDetails').innerHTML=`<div class="dialog-grid">${m.details.map(d=>`<div><b>${d[0]}</b><span>${d[1]}</span></div>`).join('')}</div>`;dialog.showModal()}));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});

const eq=document.querySelector('.equalizer');for(let i=0;i<38;i++){const bar=document.createElement('i');bar.style.height=`${18+(i*17)%65}%`;bar.style.animationDelay=`${(i%8)*-.09}s`;eq.appendChild(bar)}document.querySelector('#playSignal').addEventListener('click',e=>{const room=document.querySelector('.sound-room');room.classList.toggle('playing');e.currentTarget.textContent=room.classList.contains('playing')?'Ⅱ':'▶'});

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const metricObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target,target=+el.dataset.count;let current=0;const timer=setInterval(()=>{el.textContent=++current;if(current>=target)clearInterval(timer)},180);metricObserver.unobserve(el)}));document.querySelectorAll('[data-count]').forEach(el=>metricObserver.observe(el));

const canvas=document.querySelector('#signalField'),ctx=canvas.getContext('2d');let points=[];function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);points=Array.from({length:Math.min(55,Math.floor(innerWidth/22))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.16,vy:(Math.random()-.5)*.16}))}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);points.forEach((p,i)=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>innerWidth)p.vx*=-1;if(p.y<0||p.y>innerHeight)p.vy*=-1;for(let j=i+1;j<points.length;j++){const q=points[j],d=Math.hypot(p.x-q.x,p.y-q.y);if(d<130){ctx.strokeStyle=`rgba(81,230,255,${(1-d/130)*.075})`;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}});requestAnimationFrame(draw)}resize();draw();addEventListener('resize',resize);

const toast=document.querySelector('#placeholderToast');document.querySelectorAll('[data-placeholder]').forEach(link=>link.addEventListener('click',e=>{if(link.getAttribute('href')==='#'){e.preventDefault();toast.textContent=`Add your real ${link.dataset.placeholder} before publishing.`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2500)}}));document.querySelector('#year').textContent=new Date().getFullYear();
